plugins = []
functionsDirectory = "/Users/okembsro/ORNET/Site_ornet/Nouveau_site/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/okembsro/ORNET/Site_ornet/Nouveau_site"
publishOrigin = "default"
commandOrigin = "config"
command = "# no build command"
functions = "/Users/okembsro/ORNET/Site_ornet/Nouveau_site/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]